// import './loadin-screen.js';
// import './call-handler.js';
import './scores.js';
import './background.js';
import './title.js';
import './pokemon.js';
import './type-container.js';
import './type.js';
import './check-button.js';
import './lifes.js';
import './menu.js';
